boundary: # Boundary of the environment
  - type: 'rectangle' 
    center: [5., 5.]
    width: 10.
    height: 10.
    angle: 0.

static_obstacles: # Static obstacles in the environment
  - type: 'rectangle'
    center: [5., 5.]
    width: 2.
    height: 2.
    angle: 0.
  - type: 'circle'
    center: [2., 2.]
    radius: 1.
  - type: 'polygon'
    vertices: [[7., 2.], [8., 3.], [7., 4.], [6., 3.]]

