common_params:
    initial_state: [0., 0., 0., 0.]
    
    # the below files is exptected to be stored in /data folder of this package
    system_input_filename: "system_input.csv"
    reference_path_filename: "reference_path.csv"
    output_filename: "output.csv"
    
model_params:
    standard_params: #The required params for class Model
        num_states: 4
        num_inputs: 2
        discrete_method: "KR4"
        step_size: 0.05

    additional_params: #Specific params for the robot
        length_back: 0.23
        length_front: 0.83

    graphic_model_params: #Specific params for representing the robot in graphic world
        tractor:
            width: 0.6
            height: 0.5

        trailer:
            width: 0.8
            height: 0.5

        hitch_joint:
            radius: 0.05

        front_wheels:
            width: 0.2
            height: 0.1
        
        back_wheels:
            width: 0.2
            height: 0.1

animator_params:
    xlim_lb: -1 #Lower bound of x axis
    xlim_ub: 7  #Upper bound of x axis
    ylim_lb: -1 #Lower bound of y axis
    ylim_ub: 5  #Upper bound of y axis
    desired_frame_rate: 20 # The desired number of frames appears within a second. 
                           # The actual frame rate may differ from this value depending on number of available simulated states within a second
    speed_factor: 10  # Animation will be speeded up by this value
    repeat: False #Whether the animation repeats when the sequence of frames is completed

