num_states: 4
num_inputs: 2

length_back: 0.23
length_front: 0.83

graphic_model_params:
    tractor:
        width: 0.6
        height: 0.5

    trailer:
        width: 0.8
        height: 0.5

    hitch_joint:
        radius: 0.05

    front_wheels:
        width: 0.2
        height: 0.1
    
    back_wheels:
        width: 0.2
        height: 0.1