common_params:
    initial_state: [0., 0., 0., 0.] #Initial state of the robot [x_trailer, y_trailer, theta_trailer, hitching_angle]

    data_folder: "data"                           #The below files are expected to be stored in this folder
    system_input_filename: "system_input.csv"     #the file contains the system inputs
    reference_path_filename: "reference_path.csv" #the file contains the reference path
    output_filename: "output.csv"                 #the file contains the result of the simulation

    system_input_names: ["v", "w"]                #the columns headers of inputs in system input file.The number of elements must match with num_states  in model_params
    reference_path_names: ["x_ref", "y_ref"]      #the columns headers of reference path in reference path file.
    
model_params:
    standard_params:            #The required params for class Model
        num_states: 4           #The number of states in the model
        num_inputs: 2           #The number of inputs in the model
        discrete_method: "KR1"  #The method to discretize the continuous model
        step_size: 0.2          #The step size of the discretization

    additional_params:          #Specific params for the robot
        length_back: 0.23       #The distance between the hitch joint and the front wheels
        length_front: 0.83      #The distance between the hitch joint and the back wheels

    graphic_model_params: #Specific params for representing the robot in graphic world
        tractor:
            width: 0.6
            height: 0.5
            params:
                color: '#667BC6'
                alpha: 1.0

        trailer:
            width: 0.8
            height: 0.5
            params:
                color: '#667BC6'
                alpha: 1.0

        hitch_joint:
            radius: 0.05
            params:
                color: '#667BC6'
                alpha: 1.0

        front_wheels:
            width: 0.2
            height: 0.1
            params:
                color: '#667BC6'
                alpha: 1.0

        back_wheels:
            width: 0.2
            height: 0.1
            params:
                color: '#667BC6'
                alpha: 1.0

animator_params:
    xlim_lb: -1                         #Lower bound of x axis
    xlim_ub: 8                          #Upper bound of x axis
    ylim_lb: -1                         #Lower bound of y axis
    ylim_ub: 6                          #Upper bound of y axis
    desired_frame_rate: 20              # The desired number of frames appears within a second. 
                                        # The actual frame rate may differ from this value depending on number of available simulated states within a second
    speed_factor: 5                     # Animation will be speeded up by this value
    repeat: False                       #Whether the animation repeats when the sequence of frames is completed
    static_path_color: ['grey']         #The color of the static path
    dynamic_path_color: ['green','red'] #The color of the dynamic path
    robot_color: '#667BC6'              #The color of the robot
